module Infer where

import Common

import Control.Monad.Writer (listen)
import Control.Monad.Except (throwError)
import Data.Map.Strict as H (Map, insert, lookup, empty, fromList, singleton)

tag1 = 64002
tag2 = 68869
tag3 = 19545

  {- question 1: fresh instance function -}

freshInst :: PolyTy -> Infer MonoTy
freshInst (Forall qVars tau) = do
  -- generate fresh type variables for each quantified variable
  freshVars <- mapM (\_ -> fresh) qVars
  -- build a substitution mapping each quantified variable to a fresh TyVar
  let subst = H.fromList (zip qVars (map TyVar freshVars))
  -- apply the substitution to the body type
  return $ apply subst tau

  {- question 2: occurs check -}

occurs :: VarId -> MonoTy -> Bool
occurs i (TyVar j) = i == j
occurs i (TyConst _ tys) = any (occurs i) tys

  {- question 3: unification -}

unify :: [Constraint] -> Infer Substitution
unify [] = return substEmpty
unify (c : cs) = case c of
  -- Delete: both sides are identical type variables
  TyVar i :~: TyVar j | i == j ->
    unify cs

  -- Eliminate: left side is a type variable not in right
  TyVar i :~: tau -> do
    if occurs i tau
      then throwError $ InfiniteType i tau
      else do
        let s = substInit i tau
        -- Apply substitution to remaining constraints, then unify
        rest <- unify (map (apply s) cs)
        return $ substCompose rest s

  -- Orient: right side is a type variable, left is not
  tau :~: TyVar i ->
    unify (TyVar i :~: tau : cs)

  -- Decompose: both sides are the same type constructor
  TyConst c1 ts1 :~: TyConst c2 ts2 ->
    if c1 /= c2 || length ts1 /= length ts2
      then throwError $ Can'tMatch (TyConst c1 ts1) (TyConst c2 ts2)
      else unify (zipWith (:~:) ts1 ts2 ++ cs)

  {- question 4: type inference -}

infer :: TypeEnv -> Exp -> Infer MonoTy
infer env exp = case exp of
  -- Constants: instantiate their polytype signature
  ConstExp c ->
    freshInst (constTySig c)

  -- Variables: look up in environment, instantiate
  VarExp x -> case H.lookup x env of
    Nothing  -> throwError $ LookupError x
    Just pty -> freshInst pty

  -- Monadic operators
  MonOpExp m e -> do
    tau  <- infer env e
    mTy  <- freshInst (monopTySig m)
    -- mTy should be a function type: argTy -> resTy
    resTy <- freshTau
    constrain mTy (funTy tau resTy)
    return resTy

  -- Binary operators
  BinOpExp b e1 e2 -> do
    tau1 <- infer env e1
    tau2 <- infer env e2
    bTy  <- freshInst (binopTySig b)
    resTy <- freshTau
    constrain bTy (funTy tau1 (funTy tau2 resTy))
    return resTy

  -- If-then-else
  IfExp e1 e2 e3 -> do
    tau1 <- infer env e1
    tau2 <- infer env e2
    tau3 <- infer env e3
    constrain tau1 boolTy
    constrain tau2 tau3
    return tau2

  -- Function abstraction
  FunExp x e -> do
    argTy <- freshTau
    -- Add x with a non-quantified type to the environment
    let env' = H.insert x (polyTyOfMonoTy argTy) env
    resTy <- infer env' e
    return $ funTy argTy resTy

  -- Function application
  AppExp e1 e2 -> do
    tau1 <- infer env e1
    tau2 <- infer env e2
    resTy <- freshTau
    constrain tau1 (funTy tau2 resTy)
    return resTy

  -- Let binding: generalize the bound expression
  LetExp x e1 e2 -> do
    -- Use listen to capture constraints generated by e1
    (tau1, cs1) <- listen $ infer env e1
    -- Unify constraints from e1 to get a substitution
    s1 <- unify cs1
    -- Apply substitution and generalize in the updated environment
    let tau1'  = apply s1 tau1
        env'   = apply s1 env
        polyTy = gen env' tau1'
        env''  = H.insert x polyTy env'
    -- Infer e2 in the extended environment
    infer env'' e2

  -- Recursive let binding
  LetRecExp f x e1 e2 -> do
    -- Fresh types for f and x
    fTy  <- freshTau
    argTy <- freshTau
    -- Add f and x to env with monomorphic types
    let env' = H.insert x (polyTyOfMonoTy argTy)
              $ H.insert f (polyTyOfMonoTy fTy) env
    -- Infer the body of the recursive function
    (resTy, cs1) <- listen $ infer env' e1
    -- f's type must match argTy -> resTy
    let cs1' = (fTy :~: funTy argTy resTy) : cs1
    s1 <- unify cs1'
    -- Generalize f's type in the original environment
    let fTy'   = apply s1 fTy
        env''  = apply s1 env
        polyTy = gen env'' fTy'
        env''' = H.insert f polyTy env''
    -- Infer e2 in the extended environment
    infer env''' e2

inferInit :: TypeEnv -> Exp -> Infer PolyTy
inferInit env e = do
  (tau, constraints) <- listen $ infer env e
  substitution <- unify constraints
  return $ quantifyMonoTy $ apply substitution tau

inferDec :: TypeEnv -> Dec -> Infer (TypeEnv, PolyTy)
inferDec env (AnonDec e') = do
  tau <- inferInit env e'
  return (env, tau)
inferDec env (LetDec x e') = do
  tau <- inferInit env (LetExp x e' (VarExp x))
  return (H.insert x tau env, tau)
inferDec env (LetRec f x e') = do
  tau <- inferInit env (LetRecExp f x e' (VarExp f))
  return (H.insert f tau env, tau)